language: python
python:
  - '3.5'
  - '3.6'
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - pip install codecov
install:
       pip install ".[test]" 
script: pytest
after_success:
  - codecov
